### ISSUE TITLE
Independent Collection, Model, and Events implementation.

### ISSUE THREAD

**Issue by gaperton** [Volicon/NestedTypes#116]
There are some bugs arises from time to time when kids from backbone team playing with their sources.

It needs to be stopped. Thus, I'm gonna take stable Events, Model, and Collection implementation, freeze it, cut out things already implemented in NestedTypes, and make standalone build. Backbone will become optional dependency. Bye-bye, birdy.

So, there will be two files. nestedtypes with bullshit cut out, and backbone+ with bullshit linked in for people who need View, History, and Router.

Also, it will be great opportunity to optimize events performance for change events bubbling, and fix quirks in stupid collections design.

**Comment by far-blue** [comment]
I assume this is part of the move to separate from Backbone so you are not constantly playing catchup when Backbone's internals are modified in ways that break NestedTypes.

But a lot of the changes in Backbone these days are bug fixes - is there going to be a policy of tracking and re-applying bug fixes from Backbone into NestedTypes?

**Comment by gaperton** [comment]
Implemented in 1.3 RC.

Completely new collection implementation, about 5 times faster in average. Now you can operate with 10K elements in collections.
