### ISSUE TITLE
We though you might like to know - works great with KnockOut and KnockBack :)

### ISSUE THREAD

**Issue by far-blue** [Volicon/NestedTypes#120]
We thought you guys might be interested to know we are using NestedTypes very successfully with Knockout using the KnockBack 'glue' layer :)

**Comment by gaperton** [comment]
Nice to hear that :). Feel free to ask questions here about best practices with NestedTypes model layer, if you will need any help.

**Comment by far-blue** [comment]
Thanks :) I think some of your answers to other issues I've posted have made that clear already :) I think we are pretty happy with how it all works generally but we are still trying to understand the best approach to the sync() related methods. We can't just use the built-in REST support because we have various aggregation and authentication 'magic' going on so we are still trying to understand how much of the built-in REST support is useful to us and how much to just bypass. But having typed model attributes, deep nesting of models and easy heterogeneous collections are all huge wins for us over Backbone :)
