### ISSUE TITLE
Any release date for v1.3?

### ISSUE THREAD

**Issue by far-blue** [Volicon/NestedTypes#130]
Hello :)

We are really looking forward to the changed you mentioned in #119 regarding polymorphic creation factories etc. - have you any idea when v1.3 will be ready for us to use?

**Comment by far-blue** [comment]
Just a reminder - you need to tag a commit before Bower will see it as a release so all your release candidates for v1.3 are unavailable to anyone using Bower...

**Comment by gaperton** [comment]
Sure. Release will be done after a week.

I need to update docs for the features added. There are some incompatibilities with backbone introduced in this release, so that's important.

**Comment by gaperton** [comment]
Now!

**Comment by gaperton** [comment]
Done.

**Comment by far-blue** [comment]
Woot! great news! We are just in a release cycle but next week we'll start updating and testing the new version. The whole team's excited about the new stuff :D

**Comment by gaperton** [comment]
Check out this:
https://github.com/Volicon/NestedTypes/blob/master/docs/RelationsGuide.md
