### ISSUE TITLE
Bower: Version declared in the json (1.1.8) is different than the resolved one (1.2.2)

### ISSUE THREAD

**Issue by sheinzle** [Volicon/NestedTypes#131]
`bower.json` has wrong version number. When installing trough `bower install backbone.nestedtypes` the result is

    bower backbone.nested-types#* download https://github.com/Volicon/backbone.nestedTypes/archive/v1.2.2.tar.gz
    bower backbone.nested-types#*  extract archive.tar.gz
    bower backbone.nested-types#* mismatch Version declared in the json (1.1.8) is different than the resolved one (1.2.2)

**Comment by gaperton** [comment]
Fixed in master. Try again, reopen if it will fails.
