### ISSUE TITLE
No default store for Collection

### ISSUE THREAD

**Issue by sheinzle** [Volicon/NestedTypes#134]
When exchanging Backbone with NestedTypes no default store is set. 

It looks like Model uses Backbone as default store (`model.js:50`), however Collection does not have such a default (`collection.js:61`). Is this intended?

**Comment by BrunoWinck** [comment]
I think I get into the same issue

**Comment by gaperton** [comment]
Should be fixed in 1.3 which goes to release now, I will double check.

**Comment by gaperton** [comment]
Yes, it should be fixed.

Empty store is created in `main.js:25`. `_defaultStore` is assigned to both Model and Collection in `store.js:118`, and referenced in both Model and Collection's `getStore()`.

If you will have any further problems with anything, please open an issue.
