### ISSUE TITLE
Ownership bug / Warning, ownership error for nested objects

### ISSUE THREAD

**Issue by sheinzle** [Volicon/NestedTypes#135]
We are getting lot's of ownership warnings when trying to initialize a collection of nested models. It looks like `_owner` is sometimes not set correctly when to using `collection.reset(jsonArray)` with a JSON array.

    // bug only occurs on Nested.Model with multiple levels of hierarchy
    var TestObj = Nested.Model.extend({
      defaults : {
        outer : Nested.Model.extend({
          defaults: {
            inner: String
          }      
        })
      }
    });

    var collection = new TestObj.Collection();

    // resetting with JSON array -> _owner of .outer is not set correctly 
    collection.reset([
      {
        outer : {
          inner: "1"  
        }
      }
    ]);

    // ownership error occurs here
    collection.toJSON()

**Comment by gaperton** [comment]
Interesting. This bug may cause serious problems when working with `Stores`. How lucky I am this feature still not documented.

Will fix this asap.

**Comment by gaperton** [comment]
Okay. I executed this example in browser's console on recently deployed `1.3.0`, I see no warnings here.

Please, confirm you still experience this problem after upgrade.

**Comment by gaperton** [comment]
Ownership mechanics is completely rewritten in 2.0 alpha (develop)
