### ISSUE TITLE
LoDash compatibility

### ISSUE THREAD

**Issue by far-blue** [Volicon/NestedTypes#141]
Hello :)

do you officially test against LoDash 4.x as well as Underscore?

**Comment by gaperton** [comment]
Nope. I think I can try.

**Comment by far-blue** [comment]
We've tried running the unit tests locally and most are fine. A few tests are failing because LoDash4 removes 'thisArg' parameters from most methods. Others are failing because _.allKeys and _.pluck have been removed. Overall, prob. not a huge problem to fix :)

**Comment by gaperton** [comment]
Yes, it's not a big deal. I'll fix it.
