### ISSUE TITLE
Set property silently

### ISSUE THREAD

**Issue by Bolik** [Volicon/NestedTypes#152]
Hi,
i can set attribute silently by pass silent:true to set method. Is it a chance to do the same for simple property assignment, like model.a=1 without firing change event?

**Comment by gaperton** [comment]
No, currently you cannot pass any options to the simple assignment (and this fact is used in its optimized implementation). However, there's the special form of `set` which have the similar effect.

`model.set( 'a', 1, { silent : true })`

**Comment by Bolik** [comment]
Does it work for native properties? For example,

```
var Class = Object.extend({
    properties: {
        readOnly : function(){ return 'hello!'; },
        readWrite : {
            get : function(){ return this._value2; },
            set : function( value ){
                this._value2 = value;
            }
        }
    }
});
```

**Comment by gaperton** [comment]
Native properties are just raw JS properties, they are always silent. model.set doesn;t work for them.
