### ISSUE TITLE
merge deepGet and deepSet to get and set

### ISSUE THREAD

**Issue by gaperton** [Volicon/NestedTypes#77]
In NestedTypes, model.get( 'attr' ) and model.set( 'attr', value ) are slower than accessing attribute through native property, and in general doesn't make any sense.

However, with new NestedTypes architecture we can add support for deep references directly to .get and .set functions, and it won't affect the performance of the native props.

Additional benefit would be that proxied underscore collections functions accepting attributes will work with deep references.

**Comment by kkilictepe** [comment]
Using get and set with attr names is important for us because the name of properties change after code uglifier.

**Comment by gaperton** [comment]
It depends on the options you pass. As far as I understand, with --mangle option it will screw up only local variables. Otherwise, latest NestedTypes version from 'develop' branch wouldn't work.

**Comment by gaperton** [comment]
And need to add warning about this issue to documentation. Recent 'NestedTypes' most likely won't work at all if you will uglify everything aggressively.

**Comment by kkilictepe** [comment]
Google closure compiler ADVANCED_OPTIMIZATIONS is my headache in these days.

**Comment by gaperton** [comment]
Won't be fixed. Let's leave it as it is for now.
