### ISSUE TITLE
Support ES6 classes

### ISSUE THREAD

**Issue by gaperton** [Volicon/NestedTypes#94]
```
// Normal declaration
@Nested.attributes({
   x : 1
})
class X extend Nested.Model {

}

// Forward or recursive declaration
@Nested
class Name extend Nested.Model {

}

Name.attributes({
   x : 1
});
```

**Comment by Bartzy** [comment]
Is ES6 support planned?
Thanks!

**Comment by gaperton** [comment]
Yes. Next release will be with ES6 support. In a month, maximum two. It's quite challenging to do while keeping all the functionality and making it look nice, but it's possible. There's another ticket with details.

**Comment by gaperton** [comment]
Implemented in 'develop', to be documented.
